### ISSUE TITLE
[BUG] please add user 'www-data' in dockerfile

### ISSUE THREAD

**Issue by iwinstar** [linuxserver/docker-nginx#96] opened 2023-08-09 14:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is no 'www-data' user in /etc/passwd, only '/etc/group' has 'www-data' group.

### Expected Behavior

Wordpress needs to set wp-content folder to 'www-data' user.
Please add 'adduser -u 82 -D -S -G www-data www-data' command in dockerfile.

### Steps To Reproduce

1. OS: Ubuntu 22.04.1
2. Install docker.io: sudo apt install docker.io
3. Create docker container
4. Execute 'cat /etc/passwd | grep www-data' in container

### Environment

```markdown
- OS: Ubuntu 22.04.1
- How docker service was installed:
  sudo apt install docker.io, docker version: 20.10.25-0ubuntu1~22.04.1
```

### CPU architecture

x86-64

### Docker creation

```bash
sudo docker run -d \
  --name=nginx \
  --net=host \
  -e PUID=1001 \
  -e PGID=1002 \
  -e TZ=Asia/Shanghai \
  -v /data/docker/nginx:/config \
  --restart unless-stopped \
  linuxserver/nginx:latest
```

### Container logs

```bash
container is ok
```

**Comment by aptalca** [comment] 2023-08-09 14:59
> Wordpress needs to set wp-content folder to 'www-data' user

??? Wordpress is just a php app. It doesn't care what user runs it. Drop it into the /config/www folder, edit the default site conf as necessary, restart the container and browse to the wizard.

https://docs.linuxserver.io/general/swag#hosting-a-wordpress-site

Closing as it's not a bug

**Closed by aptalca** 2023-08-09 14:59 UTC
